// src/shared/api/mock-data.js
import { 
  OPPORTUNITY_TYPE_TO_NUMBER, 
  WORK_FORMAT_TO_NUMBER, 
  EXPERIENCE_LEVEL_TO_NUMBER,
  MODERATION_STATUS_TO_NUMBER 
} from '@/shared/constants';

// Фиксированные ID (не меняются между сессиями)
export const FIXED_IDS = {
  YANDEX_EMPLOYER: '11111111-1111-4111-8111-111111111111',
  VK_EMPLOYER: '22222222-2222-4222-8222-222222222222',
  SBER_EMPLOYER: '33333333-3333-4333-8333-333333333333',
  TINKOFF_EMPLOYER: '44444444-4444-4444-8444-444444444444',
  OZON_EMPLOYER: '55555555-5555-4555-8555-555555555555',
  AVITO_EMPLOYER: '66666666-6666-4666-8666-666666666666',
  ROGA_EMPLOYER: '77777777-7777-4777-8777-777777777777',
  
  OPPORTUNITY_1: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  OPPORTUNITY_2: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
  OPPORTUNITY_3: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
  OPPORTUNITY_4: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
  OPPORTUNITY_5: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
  OPPORTUNITY_6: 'ffffffff-ffff-4fff-8fff-ffffffffffff',
  OPPORTUNITY_7: 'gggggggg-gggg-4ggg-8ggg-gggggggggggg',
};

// Данные работодателей
const employers = {
  yandex: {
    id: FIXED_IDS.YANDEX_EMPLOYER,
    companyName: 'Яндекс',
    description: 'Крупнейшая IT-компания в России',
    website: 'https://yandex.ru/jobs',
    contactEmail: 'hr@yandex-team.ru',
    contactPhone: '+7 (495) 739-70-00',
    verifiedStatus: 1,
  },
  vk: {
    id: FIXED_IDS.VK_EMPLOYER,
    companyName: 'VK Tech',
    description: 'Технологическая компания',
    website: 'https://vk.com/careers',
    contactEmail: 'internship@vk.team',
    contactPhone: '+7 (812) 123-45-67',
    verifiedStatus: 1,
  },
  sber: {
    id: FIXED_IDS.SBER_EMPLOYER,
    companyName: 'СберТех',
    description: 'Технологическая дочка Сбера',
    website: 'https://sbertech.ru/career',
    contactEmail: 'mentorship@sbertech.ru',
    contactPhone: '+7 (800) 555-35-35',
    verifiedStatus: 1,
  },
  tinkoff: {
    id: FIXED_IDS.TINKOFF_EMPLOYER,
    companyName: 'Тинькофф',
    description: 'Экосистема финансовых и lifestyle сервисов',
    website: 'https://tinkoff.ru/career',
    contactEmail: 'hr@tinkoff.ru',
    contactPhone: '+7 (843) 200-00-00',
    verifiedStatus: 0,
  },
  ozon: {
    id: FIXED_IDS.OZON_EMPLOYER,
    companyName: 'Ozon',
    description: 'Маркетплейс',
    website: 'https://corp.ozon.ru/career',
    contactEmail: 'career@ozon.ru',
    contactPhone: '+7 (383) 123-45-67',
    verifiedStatus: 1,
  },
  avito: {
    id: FIXED_IDS.AVITO_EMPLOYER,
    companyName: 'Авито',
    description: 'Классифайд',
    website: 'https://team.avito.ru/',
    contactEmail: 'mentors@avito.ru',
    contactPhone: '+7 (812) 333-22-11',
    verifiedStatus: 1,
  },
  roga: {
    id: FIXED_IDS.ROGA_EMPLOYER,
    companyName: 'ООО Рога и Копыта',
    description: 'Разработка ПО',
    website: 'https://roga-kopyta.ru/career',
    contactEmail: 'hr@roga-kopyta.ru',
    contactPhone: '+7 (495) 555-55-55',
    verifiedStatus: 1,
  },
};

// Теги с фиксированными ID
const tagsList = [
  { id: 't1', name: 'React' },
  { id: 't2', name: 'TypeScript' },
  { id: 't3', name: 'Redux' },
  { id: 't4', name: 'HTML/CSS' },
  { id: 't5', name: 'Jest' },
  { id: 't6', name: 'Webpack' },
  { id: 't7', name: 'Java' },
  { id: 't8', name: 'Spring' },
  { id: 't9', name: 'PostgreSQL' },
  { id: 't10', name: 'Git' },
  { id: 't11', name: 'Maven' },
  { id: 't12', name: 'REST API' },
  { id: 't13', name: 'Карьерное консультирование' },
  { id: 't14', name: 'Soft skills' },
  { id: 't15', name: 'Собеседования' },
  { id: 't16', name: 'CV review' },
  { id: 't17', name: 'Технические интервью' },
  { id: 't18', name: 'SQL' },
  { id: 't19', name: 'Python' },
  { id: 't20', name: 'Tableau' },
  { id: 't21', name: 'Статистика' },
  { id: 't22', name: 'pandas' },
  { id: 't23', name: 'Airflow' },
  { id: 't24', name: 'Swift' },
  { id: 't25', name: 'iOS' },
  { id: 't26', name: 'Xcode' },
  { id: 't27', name: 'UIKit' },
  { id: 't28', name: 'Docker' },
  { id: 't29', name: 'Kubernetes' },
  { id: 't30', name: 'CI/CD' },
  { id: 't31', name: 'Linux' },
  { id: 't32', name: 'GitLab CI' },
  { id: 't33', name: 'Terraform' },
  { id: 't34', name: 'PHP' },
  { id: 't35', name: 'Laravel' },
  { id: 't36', name: 'MySQL' },
  { id: 't37', name: 'Redis' },
  { id: 't38', name: 'RabbitMQ' },
];

// Функция для получения тегов по названиям
const getTagsByName = (names) => {
  return tagsList.filter(tag => names.includes(tag.name));
};

export const opportunities = [
  {
    ID: FIXED_IDS.OPPORTUNITY_1,
    EmployerID: employers.yandex.id,
    Employer: employers.yandex,
    CuratorID: null,
    Curator: null,
    Tags: getTagsByName(['React', 'TypeScript', 'Redux', 'HTML/CSS', 'Jest', 'Webpack']),
    Title: "Frontend-разработчик (React)",
    Description: "Ищем разработчика для работы над интерфейсами высоконагруженного сервиса. Требуется опыт с React, TypeScript, знание стейт-менеджеров. Проект федерального масштаба.\n\nОбязанности:\n• Разработка новых модулей и компонентов\n• Оптимизация производительности\n• Участие в код-ревью\n• Написание unit-тестов\n\nУсловия:\n• Оформление по ТК РФ\n• ДМС со стоматологией\n• Гибкий график работы\n• Релокация (по желанию)",
    OpportunityType: OPPORTUNITY_TYPE_TO_NUMBER['Вакансия'],
    WorkFormat: WORK_FORMAT_TO_NUMBER['Гибрид'],
    LocationCity: "Москва",
    Latitude: 55.7558,
    Longitude: 37.6176,
    SalaryMin: 200000,
    SalaryMax: 280000,
    ExperienceLevel: EXPERIENCE_LEVEL_TO_NUMBER['Middle'],
    ModerationStatus: MODERATION_STATUS_TO_NUMBER['Подтверждено'],
    ExpiresAt: "2026-06-30T23:59:59Z",
    EventDateStart: null,
    EventDateEnd: null,
    CreatedAt: "2026-03-15T10:00:00Z",
    UpdatedAt: "2026-03-15T10:00:00Z",
  },
  {
    ID: FIXED_IDS.OPPORTUNITY_2,
    EmployerID: employers.vk.id,
    Employer: employers.vk,
    CuratorID: null,
    Curator: null,
    Tags: getTagsByName(['Java', 'Spring', 'PostgreSQL', 'Git', 'Maven', 'REST API']),
    Title: "Java-стажёр",
    Description: "Стажировка для студентов старших курсов и недавних выпускников. Работа над микросервисами, участие в код-ревью, написание тестов. Возможно дальнейшее трудоустройство.\n\nЧем предстоит заниматься:\n• Разработка микросервисов на Java\n• Участие в планировании задач\n• Написание технической документации\n\nМы предлагаем:\n• Наставничество от senior-разработчиков\n• Гибкий график (20-40 часов в неделю)\n• Возможность перехода в штат",
    OpportunityType: OPPORTUNITY_TYPE_TO_NUMBER['Стажировка'],
    WorkFormat: WORK_FORMAT_TO_NUMBER['Офис'],
    LocationCity: "Санкт-Петербург",
    Latitude: 59.9343,
    Longitude: 30.3351,
    SalaryMin: 80000,
    SalaryMax: 120000,
    ExperienceLevel: EXPERIENCE_LEVEL_TO_NUMBER['Junior'],
    ModerationStatus: MODERATION_STATUS_TO_NUMBER['Подтверждено'],
    ExpiresAt: "2026-05-15T23:59:59Z",
    EventDateStart: null,
    EventDateEnd: null,
    CreatedAt: "2026-03-10T10:00:00Z",
    UpdatedAt: "2026-03-12T10:00:00Z",
  },
  {
    ID: FIXED_IDS.OPPORTUNITY_3,
    EmployerID: null,
    Employer: null,
    CuratorID: '55555555-5555-4555-8555-555555555555',
    Curator: null,
    Tags: getTagsByName(['Карьерное консультирование', 'Soft skills', 'Собеседования', 'CV review', 'Технические интервью']),
    Title: "Менторская программа: Карьера в IT",
    Description: "Индивидуальное менторство от senior-разработчиков. Помощь с выбором стека, подготовкой к собеседованиям, разбор резюме. Длительность 3 месяца.\n\nЧто вас ждёт:\n• 12 индивидуальных сессий с ментором\n• Разбор реальных кейсов\n• Карьерные консультации\n• Помощь с подготовкой к техническим интервью\n\nПрограмма подойдёт:\n• Студентам последних курсов\n• Выпускникам без опыта\n• Junior-разработчикам, желающим вырасти до Middle",
    OpportunityType: OPPORTUNITY_TYPE_TO_NUMBER['Менторство'],
    WorkFormat: WORK_FORMAT_TO_NUMBER['Удалённо'],
    LocationCity: "Москва",
    Latitude: 55.7558,
    Longitude: 37.6176,
    SalaryMin: null,
    SalaryMax: null,
    ExperienceLevel: EXPERIENCE_LEVEL_TO_NUMBER['Junior'],
    ModerationStatus: MODERATION_STATUS_TO_NUMBER['Подтверждено'],
    ExpiresAt: "2026-12-31T23:59:59Z",
    EventDateStart: "2026-04-01T10:00:00Z",
    EventDateEnd: "2026-06-30T18:00:00Z",
    CreatedAt: "2026-03-01T10:00:00Z",
    UpdatedAt: "2026-03-02T10:00:00Z",
  },
  {
    ID: FIXED_IDS.OPPORTUNITY_4,
    EmployerID: employers.tinkoff.id,
    Employer: employers.tinkoff,
    CuratorID: null,
    Curator: null,
    Tags: getTagsByName(['SQL', 'Python', 'Tableau', 'Статистика', 'pandas', 'Airflow']),
    Title: "Аналитик данных (стажёр)",
    Description: "Сбор и анализ данных, построение дашбордов, работа с большими данными. Хорошее знание SQL и Python (pandas). Работа в офисе или гибрид.\n\nЗадачи:\n• Формирование аналитических отчётов\n• Построение дашбордов в Tableau\n• Оптимизация SQL-запросов\n• Участие в A/B-тестировании\n\nТребования:\n• Знание Python (pandas, numpy)\n• Уверенное владение SQL\n• Понимание статистики\n\nУсловия:\n• Гибкий график\n• Обучение за счёт компании\n• Корпоративные скидки",
    OpportunityType: OPPORTUNITY_TYPE_TO_NUMBER['Стажировка'],
    WorkFormat: WORK_FORMAT_TO_NUMBER['Гибрид'],
    LocationCity: "Казань",
    Latitude: 55.7887,
    Longitude: 49.1221,
    SalaryMin: 90000,
    SalaryMax: 140000,
    ExperienceLevel: EXPERIENCE_LEVEL_TO_NUMBER['Junior'],
    ModerationStatus: MODERATION_STATUS_TO_NUMBER['На модерации'],
    ExpiresAt: "2026-04-20T23:59:59Z",
    EventDateStart: null,
    EventDateEnd: null,
    CreatedAt: "2026-03-14T10:00:00Z",
    UpdatedAt: "2026-03-14T10:00:00Z",
  },
  {
    ID: FIXED_IDS.OPPORTUNITY_5,
    EmployerID: employers.ozon.id,
    Employer: employers.ozon,
    CuratorID: null,
    Curator: null,
    Tags: getTagsByName(['Swift', 'iOS', 'Xcode', 'UIKit', 'Git', 'REST API']),
    Title: "iOS стажировка",
    Description: "Ищем увлеченных студентов для разработки мобильных приложений. Знание Swift, опыт работы с Xcode, понимание UI/UX. Наставничество от лидов.\n\nПроекты:\n• Разработка новых фич\n• Рефакторинг кода\n• Участие в спринтах\n\nТребования:\n• Знание Swift\n• Опыт работы с Xcode\n• Понимание UIKit/SwiftUI\n• Базовые знания Git\n\nМы предлагаем:\n• Гибкий график\n• Бесплатные обеды\n• Участие в реальных проектах",
    OpportunityType: OPPORTUNITY_TYPE_TO_NUMBER['Стажировка'],
    WorkFormat: WORK_FORMAT_TO_NUMBER['Офис'],
    LocationCity: "Новосибирск",
    Latitude: 55.0084,
    Longitude: 82.9357,
    SalaryMin: 70000,
    SalaryMax: 110000,
    ExperienceLevel: EXPERIENCE_LEVEL_TO_NUMBER['Junior'],
    ModerationStatus: MODERATION_STATUS_TO_NUMBER['Подтверждено'],
    ExpiresAt: "2026-05-01T23:59:59Z",
    EventDateStart: null,
    EventDateEnd: null,
    CreatedAt: "2026-03-05T10:00:00Z",
    UpdatedAt: "2026-03-06T10:00:00Z",
  },
  {
    ID: FIXED_IDS.OPPORTUNITY_6,
    EmployerID: employers.avito.id,
    Employer: employers.avito,
    CuratorID: null,
    Curator: null,
    Tags: getTagsByName(['Docker', 'Kubernetes', 'CI/CD', 'Linux', 'GitLab CI', 'Terraform']),
    Title: "DevOps ментор",
    Description: "Практикующие DevOps инженеры помогут разобраться в CI/CD, Docker, Kubernetes, облачных провайдерах. Индивидуальный план развития.\n\nПрограмма менторства:\n• 8 индивидуальных сессий\n• Разбор реальных инфраструктурных кейсов\n• Помощь в выборе сертификаций\n\nТемы для изучения:\n• Docker и контейнеризация\n• Kubernetes (основы и продвинутые темы)\n• CI/CD пайплайны\n• Облачные провайдеры (Yandex Cloud, AWS)\n\nДля кого:\n• Системные администраторы\n• Разработчики, желающие перейти в DevOps\n• Студенты технических специальностей",
    OpportunityType: OPPORTUNITY_TYPE_TO_NUMBER['Менторство'],
    WorkFormat: WORK_FORMAT_TO_NUMBER['Удалённо'],
    LocationCity: "Санкт-Петербург",
    Latitude: 59.9343,
    Longitude: 30.3351,
    SalaryMin: null,
    SalaryMax: null,
    ExperienceLevel: EXPERIENCE_LEVEL_TO_NUMBER['Middle'],
    ModerationStatus: MODERATION_STATUS_TO_NUMBER['Подтверждено'],
    ExpiresAt: "2026-08-01T23:59:59Z",
    EventDateStart: "2026-04-10T10:00:00Z",
    EventDateEnd: "2026-07-10T18:00:00Z",
    CreatedAt: "2026-03-08T10:00:00Z",
    UpdatedAt: "2026-03-08T10:00:00Z",
  },
  {
    ID: FIXED_IDS.OPPORTUNITY_7,
    EmployerID: employers.roga.id,
    Employer: employers.roga,
    CuratorID: null,
    Curator: null,
    Tags: getTagsByName(['PHP', 'Laravel', 'MySQL', 'Redis', 'Docker', 'RabbitMQ']),
    Title: "Middle PHP разработчик",
    Description: "Разработка высоконагруженных сервисов на PHP. Требуется опыт с Laravel, MySQL, Redis. Работа в команде профессионалов.\n\nОбязанности:\n• Разработка новых функций сервиса\n• Оптимизация производительности\n• Написание тестов\n• Участие в архитектурных обсуждениях\n\nТребования:\n• Опыт PHP 7/8 от 3 лет\n• Хорошее знание Laravel\n• Понимание работы MySQL и Redis\n• Опыт работы с высокими нагрузками\n\nУсловия:\n• Полная удалённая работа\n• Официальное оформление\n• Ежегодная премия",
    OpportunityType: OPPORTUNITY_TYPE_TO_NUMBER['Вакансия'],
    WorkFormat: WORK_FORMAT_TO_NUMBER['Удалённо'],
    LocationCity: "Москва",
    Latitude: 55.7558,
    Longitude: 37.6176,
    SalaryMin: 180000,
    SalaryMax: 250000,
    ExperienceLevel: EXPERIENCE_LEVEL_TO_NUMBER['Middle'],
    ModerationStatus: MODERATION_STATUS_TO_NUMBER['Подтверждено'],
    ExpiresAt: "2026-04-30T23:59:59Z",
    EventDateStart: null,
    EventDateEnd: null,
    CreatedAt: "2026-03-12T10:00:00Z",
    UpdatedAt: "2026-03-12T10:00:00Z",
  },
];

export const tags = tagsList;
export const employersList = Object.values(employers);